package io.droidmcp.all

import android.content.Context
import com.google.common.truth.Truth.assertThat
import com.google.common.truth.Truth.assertWithMessage
import io.droidmcp.core.McpTool
import io.droidmcp.core.ToolParameter
import io.droidmcp.shell.NoOpShellBackend
import io.droidmcp.shell.ShellBackend
import io.droidmcp.shell.ShellPolicy
import io.github.classgraph.ClassGraph
import io.mockk.mockk
import io.mockk.mockkClass
import org.junit.jupiter.api.Test
import java.io.File
import java.lang.reflect.Constructor

/**
 * Guards the per-tool wire contract from docs/VERSIONING.md: every tool's name, annotations and
 * parameters (name, type, required, items, enum, range). Descriptions are deliberately left out.
 *
 * The snapshot lives in `droid-mcp-all/api/tool-contract.txt`. After an intended change run
 * `./gradlew :droid-mcp-all:testDebugUnitTest -PupdateToolContract` and commit the diff.
 */
class ToolContractTest {

    @Test
    fun `tool wire contract matches the committed snapshot`() {
        val tools = discoverTools()
        assertThat(tools.map { it.name }).containsNoDuplicates()

        val actual = render(tools)
        val file = File(System.getProperty("droidmcp.contractFile") ?: error("droidmcp.contractFile not set"))
        if (System.getProperty("droidmcp.updateContract") == "true") {
            file.parentFile.mkdirs()
            file.writeText(actual)
            return
        }
        check(file.exists()) {
            "No snapshot at ${file.path}. Run ./gradlew :droid-mcp-all:testDebugUnitTest -PupdateToolContract and commit it."
        }
        assertWithMessage(
            "Tool wire contract changed. Renaming or removing a tool, parameter or type breaks clients " +
                "(docs/VERSIONING.md). If intended, rerun with -PupdateToolContract and commit api/tool-contract.txt.",
        ).that(actual).isEqualTo(file.readText())
    }

    private fun discoverTools(): List<McpTool> =
        ClassGraph().acceptPackages("io.droidmcp").enableClassInfo().scan().use { scan ->
            scan.getClassesImplementing(McpTool::class.java.name)
                .filter { !it.isAbstract && !it.isInterface && !it.isAnonymousInnerClass }
                .map { instantiate(it.loadClass()) }
        }.sortedBy { it.name }

    private fun instantiate(type: Class<*>): McpTool {
        type.kotlin.objectInstance?.let { return it as McpTool }
        val ctor = type.declaredConstructors
            .filterNot(Constructor<*>::isSynthetic)
            .maxBy { it.parameterCount }
            .apply { isAccessible = true }
        val args = ctor.parameterTypes.map(::argumentFor).toTypedArray()
        return ctor.newInstance(*args) as McpTool
    }

    private fun argumentFor(type: Class<*>): Any? = when {
        Context::class.java.isAssignableFrom(type) -> mockk<Context>(relaxed = true)
        type == ShellBackend::class.java -> NoOpShellBackend
        type == ShellPolicy::class.java -> ShellPolicy.RECOMMENDED
        type == Boolean::class.javaPrimitiveType -> false
        type == Int::class.javaPrimitiveType -> 0
        type == Long::class.javaPrimitiveType -> 0L
        type == String::class.java -> ""
        type == Function0::class.java -> { -> null }
        else -> mockkOf(type)
    }

    private fun mockkOf(type: Class<*>): Any = mockkClass(type.kotlin, relaxed = true)

    private fun render(tools: List<McpTool>): String = buildString {
        appendLine("# Tool wire contract — generated by ToolContractTest. Do not edit by hand.")
        appendLine("# ${tools.size} tools")
        tools.forEach { tool ->
            val a = tool.annotations
            val hints = listOfNotNull(
                "readOnly".takeIf { a.readOnlyHint },
                "destructive".takeIf { a.destructiveHint },
                "idempotent".takeIf { a.idempotentHint },
                "openWorld".takeIf { a.openWorldHint },
            )
            appendLine()
            append(tool.name)
            if (hints.isNotEmpty()) append("  [${hints.joinToString(", ")}]")
            if (tool.outputSchema != null) append("  outputSchema")
            appendLine()
            tool.parameters.forEach { appendLine("  ${renderParam(it)}") }
        }
    }

    private fun renderParam(p: ToolParameter): String = buildString {
        append("${p.name}: ${p.type.jsonType}")
        p.itemsType?.let { append("<${it.jsonType}>") }
        if (p.required) append(" required")
        p.enumValues?.let { append(" enum=${it.joinToString("|")}") }
        p.minimum?.let { append(" min=${fmt(it)}") }
        p.maximum?.let { append(" max=${fmt(it)}") }
    }

    private fun fmt(d: Double) = if (d == Math.floor(d)) d.toLong().toString() else d.toString()
}
